server:
  port: 8088
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        pool:
          type: fixed
          max-connections: 3000
          acquire-timeout: 8000
          max-life-time: 300s
          max-idle-time: 10s
        connect-timeout: 30000
        response-timeout: 60s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1

    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceZone: gw-service-api
        register: false
        registerHealthCheck: false
        tags: gw-service-api-tags
        healthCheckPath: /
        healthCheckInterval: 15s
      config:
        enabled: false
      retry:
        enabled: true
        initialInterval: 2
  data:
    redis:
      host: localhost
      port: 6379

